# Predict labels for Issues using a trained model
name: "Labeler: Predict (Issues)"

on:
  # Only automatically predict area labels when issues are first opened
  issues:
    types: opened

  # Allow dispatching the workflow via the Actions UI, specifying ranges of numbers
  workflow_dispatch:
    inputs:
      issues:
        description: "Issue Numbers (comma-separated list of ranges)."
        required: true
      cache_key:
        description: "The cache key suffix to use for restoring the model. Defaults to 'ACTIVE'."
        required: true
        default: "ACTIVE"

env:
  # Do not allow failure for jobs triggered automatically (as this causes red noise on the workflows list)
  ALLOW_FAILURE: ${{ github.event_name == 'workflow_dispatch' }}

  THRESHOLD: 0.40
  DEFAULT_LABEL: "needs-area-label"

jobs:
  predict-issue-label:
    # Do not automatically run the workflow on forks outside the 'dotnet' org
    if: ${{ github.event_name == 'workflow_dispatch' || github.repository_owner == 'dotnet' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Restore category issues model from cache"
        id: restore-category-model
        uses: dotnet/issue-labeler/restore@main
        with:
          type: category-issues
          fail-on-cache-miss: ${{ env.ALLOW_FAILURE }}
          quiet: true

      - name: "Restore service issues model from cache"
        id: restore-service-model
        uses: dotnet/issue-labeler/restore@main
        with:
          type: service-issues
          fail-on-cache-miss: ${{ env.ALLOW_FAILURE }}
          quiet: true

      - name: "Predict issue labels"
        id: prediction
        if: ${{ steps.restore-category-model.outputs.cache-hit == 'true' || steps.restore-service-model.outputs.cache-hit == 'true' }}
        uses: dotnet/issue-labeler/predict@main
        with:
          issues: ${{ inputs.issues || github.event.issue.number }}
          threshold: ${{ env.THRESHOLD }}
          default_label: ${{ env.DEFAULT_LABEL }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: ${{ !env.ALLOW_FAILURE }}
